tabs:
  main:
    display: Primär
    sections:
      -
        display: 'Titel etc.'
        fields:
          -
            handle: website_title
            field:
              type: text
              display: Website-TItel
              instructions: 'Wird z.B. im manifest.json für PWA verwendet.'
              localizable: true
      -
        display: Logos
        fields:
          -
            handle: main_logo
            field:
              max_files: 1
              container: assets
              folder: logos
              type: assets
              display: Haupt-Logo
              localizable: false
              width: 50
          -
            handle: main_logo_dark
            field:
              max_files: 1
              container: assets
              folder: logos
              type: assets
              display: 'Haupt-Logo Dark Mode'
              localizable: false
              width: 50
  social_media_tab:
    display: 'Social Media'
    sections:
      -
        fields:
          -
            handle: social_media_links
            field:
              collapse: accordion
              fullscreen: false
              button_label: 'Social Media Link hinzufügen'
              type: replicator
              display: 'Social Media Links'
              localizable: false
              sets:
                neue_setgruppe:
                  display: 'Neue Setgruppe'
                  sets:
                    social_media_link:
                      display: 'Social Media Link'
                      icon: social-share
                      fields:
                        -
                          handle: link
                          field:
                            type: text
                            display: Link
                            localizable: false
                            width: 50
                        -
                          handle: link_text
                          field:
                            type: text
                            display: Link-Text
                            localizable: false
                            width: 50
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            handle: seo_explanation
            field:
              type: section
              instructions: 'Dies sind die Default-Einstellungen. Sie können pro Seite überschrieben werden.'
              localizable: false
              display: 'Default SEO Einstellungen'
          -
            import: seo
  favicons_tab:
    display: Favicons
    sections:
      -
        display: Favicons
        fields:
          -
            import: favicons
